agentToken: ""

nodeSelector: {}
tolerations: []

config:
  org: ""

resources:
  requests:
    cpu: 100m
    memory: 100Mi

labels: {}

annotations: {}

secretsMetadata: {}

serviceAccountMetadata: {}

monitoring:
  deployGrafanaDashboard: true
  podMonitor:
    deploy: true
